In [3]:
import paratext
import pandas as pd

In [7]:
def fast_read_csv(path):
    df = paratext.load_csv_to_pandas(path, cat_names = ['ticker', 'date', 'lastupdated'])

    df.set_index(0, inplace=True, drop=True)

    df_correct_dict = {}
    for column_name in df.index.tolist():
        df_correct_dict[column_name] = df.loc[column_name, :].tolist()[0]

    df_correct = pd.DataFrame(df_correct_dict)

    for index, type_value in df_correct.dtypes.iteritems():
        if type_value == object:
            df_correct.loc[:, index] = df_correct.loc[:, index].apply(lambda x: x.decode("utf-8") )

    return df_correct

In [13]:
import pandas as pd
import time
start = time.time()
frame = pd.read_csv(r'E:\data\quandl\sharadar\symbol_list\SHARADAR_SEP_5659e77b6ffc1f36d023b6a3987da31c.csv')
end = time.time()
print(end-start)

44.88540601730347

In [17]:
start = time.time()
frame = fast_read_csv(r'E:\data\quandl\sharadar\fund_price\SHARADAR_SFP_233bb9e7eb4cd1e64e2ab1117cd9dffa.csv')
end = time.time()
print(end-start)

18.25005054473877

In [18]:
frame.loc[:, "date"] = pd.to_datetime(frame['date'], format='%Y-%m-%d')
frame.set_index("date", drop=True, inplace=True)

In [19]:
frame.sort_index(inplace=True)

In [20]:
frame[frame.loc[:, "ticker"] == "SPY"]

,ticker,open,high,low,close,volume,dividends,closeunadj,lastupdated
date,,,,,,,,,
1997-12-31,SPY,96.875000,97.625000,96.688004,97.063004,4359500.0,0.0,97.063004,2020-08-06
1998-01-02,SPY,97.313004,97.655998,96.530998,97.563004,2360900.0,0.0,97.563004,2020-08-06
1998-01-05,SPY,97.844002,98.438004,96.780998,97.780998,4191800.0,0.0,97.780998,2020-08-06
1998-01-06,SPY,97.250000,97.280998,96.188004,96.219002,3154900.0,0.0,96.219002,2020-08-06
1998-01-07,SPY,96.094002,96.719002,95.219002,96.469002,4424200.0,0.0,96.469002,2020-08-06
...,...,...,...,...,...,...,...,...,...
2021-01-25,SPY,383.670013,384.769989,378.459991,384.390015,70172000.0,0.0,384.390015,2021-01-25
2021-01-26,SPY,385.410004,385.850006,383.540009,383.790009,42235068.0,0.0,383.790009,2021-01-26
2021-01-27,SPY,380.220001,380.320007,372.010010,374.410004,122536312.0,0.0,374.410004,2021-01-27
2021-01-28,SPY,376.359985,381.929993,375.890015,377.630005,93773400.0,0.0,377.630005,2021-01-28
2021-01-29,SPY,375.630005,376.670013,368.269989,370.070007,126601432.0,0.0,370.070007,2021-01-29